# Generated by Django 5.2.17 on 2026-09-21 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Logical service name, e.g. user-service', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('lb_method', models.CharField(choices=[('round_robin', 'Round Robin'), ('least_conn', 'Least Connections'), ('ip_hash', 'IP Hash')], default='round_robin', max_length=20, verbose_name='Load balancing method')),
                ('keepalive_connections', models.IntegerField(default=32, help_text='Idle connections each worker keeps open to this backend. Size it to peak concurrent in-flight requests per worker, not total.')),
                ('keepalive_requests', models.IntegerField(default=1000, help_text='Requests to send down one connection before reopening it')),
                ('keepalive_timeout', models.IntegerField(default=60, help_text='Seconds an idle connection to this backend is kept open')),
                ('health_check_enabled', models.BooleanField(default=True)),
                ('health_check_path', models.CharField(default='/health', help_text='HTTP path to probe for health checks', max_length=255)),
                ('health_check_interval', models.IntegerField(default=10, help_text='Seconds between health checks')),
                ('health_check_timeout', models.IntegerField(default=5, help_text='Seconds before a health check is considered failed')),
                ('drain_unhealthy', models.BooleanField(default=False, help_text="Write failing instances out of the gateway config as 'down'. Off by default: Nginx already fails over on its own, in real time, and every drain costs a reload.")),
                ('unhealthy_threshold', models.IntegerField(default=3, help_text='Consecutive failed probes before an instance is drained')),
                ('healthy_threshold', models.IntegerField(default=2, help_text='Consecutive successful probes before a drained instance returns')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BackendInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(help_text='IP address of the backend instance')),
                ('port', models.IntegerField(default=8080, help_text='Port the backend instance listens on')),
                ('weight', models.IntegerField(default=1, help_text='Relative weight for load balancing (higher = more traffic)')),
                ('max_fails', models.IntegerField(default=3, help_text='Number of failed requests before marking as unavailable')),
                ('fail_timeout', models.IntegerField(default=10, help_text='Seconds to wait before retrying a failed upstream')),
                ('is_healthy', models.BooleanField(db_index=True, default=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('consecutive_successes', models.IntegerField(default=0)),
                ('is_draining', models.BooleanField(db_index=True, default=False, help_text="Rendered as 'down' in the upstream block, so it takes no new traffic")),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('last_health_status_code', models.IntegerField(blank=True, null=True)),
                ('last_health_response_ms', models.FloatField(blank=True, help_text='Response time of the last health check in milliseconds', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='backends.backend')),
            ],
            options={
                'ordering': ['backend', 'address', 'port'],
                'unique_together': {('backend', 'address', 'port')},
            },
        ),
    ]
