# Generated by Django 5.2.17 on 2026-09-21 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backends', '0001_initial'),
        ('domains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigDeployLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('testing', 'Testing'), ('deployed', 'Deployed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('config_snapshot', models.TextField(help_text='Full rendered Nginx config at time of deploy')),
                ('error_output', models.TextField(blank=True, default='', help_text='Output from nginx -t if the test failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deployed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('path_prefix', 'Path Prefix'), ('exact_path', 'Exact Path'), ('regex', 'Regular Expression')], default='path_prefix', max_length=20)),
                ('match_value', models.CharField(help_text='Path prefix (e.g. /api/v1) or exact path (e.g. /health)', max_length=255)),
                ('priority', models.IntegerField(db_index=True, default=100, help_text='Lower number = higher priority (evaluated first)')),
                ('cache_enabled', models.BooleanField(default=False, help_text='Enable HTTP caching at the gateway for this route')),
                ('cache_ttl', models.IntegerField(default=600, help_text='Cache TTL in seconds (for 200/302 responses)')),
                ('cache_bypass_auth', models.BooleanField(default=True, help_text='Bypass cache when Authorization header or session cookie is present')),
                ('cache_min_uses', models.IntegerField(default=1, help_text='Store a response only after this many requests for it. Raising it keeps one-off URLs from filling the cache.')),
                ('cache_key_headers', models.JSONField(blank=True, default=list, help_text='Request headers to fold into the cache key, e.g. ["Accept-Encoding"]. Any header this route switches on must be listed here or the cache will serve one variant to every caller.')),
                ('cache_ignore_upstream_control', models.BooleanField(default=False, help_text="Cache even when the backend sends Cache-Control: no-cache. Off by default because it overrides the backend's own judgement.")),
                ('cache_allow_authenticated', models.BooleanField(default=False, help_text='Acknowledgement that caching authenticated responses is intended. Required before cache_bypass_auth can be turned off.')),
                ('strip_prefix', models.BooleanField(default=False, help_text='Strip the match_value prefix before forwarding to backend')),
                ('custom_headers', models.JSONField(blank=True, default=dict, help_text='Extra headers to send to the backend (JSON object)')),
                ('proxy_buffering', models.BooleanField(default=True, help_text='Enable response buffering (disable for WebSocket/SSE)')),
                ('proxy_read_timeout', models.IntegerField(default=60, help_text='Read timeout in seconds for this route')),
                ('rate_limit_enabled', models.BooleanField(default=False)),
                ('rate_limit_rps', models.IntegerField(default=100, help_text='Requests per second allowed per client IP')),
                ('rate_limit_burst', models.IntegerField(default=200, help_text='How many requests may arrive above the rate before any are rejected')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='backends.backend')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='domains.domain')),
            ],
            options={
                'ordering': ['domain', 'priority', 'match_value'],
                'unique_together': {('domain', 'match_type', 'match_value')},
            },
        ),
        migrations.CreateModel(
            name='HeaderRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_name', models.CharField(default='X-Route', help_text='Request header to switch on, e.g. X-Route', max_length=64)),
                ('header_value', models.CharField(help_text='Value that sends the request to this backend instead', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_routes', to='backends.backend')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_routes', to='routing.routingrule')),
            ],
            options={
                'ordering': ['rule', 'header_name', 'header_value'],
                'unique_together': {('rule', 'header_name', 'header_value')},
            },
        ),
    ]
