# Generated by Django 5.2.17 on 2026-09-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routingrule',
            name='cache_ignore_query_string',
            field=models.BooleanField(default=False, help_text='Cache by path alone, ignoring the query string. Without this, a flood of requests carrying random query parameters misses on every one and hands the whole load straight to the backend -- the cache stops being a shield and becomes a liability. Only correct where the query string does not change the response.'),
        ),
    ]
