# Generated by Django 5.2.17 on 2026-09-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_routingrule_cache_ignore_query_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingrule',
            name='proxy_read_timeout',
            field=models.IntegerField(default=60, help_text='Seconds to wait for the backend to respond. On a streaming route this bounds idle time on the open connection instead, so a WebSocket that goes quiet for longer than this is closed -- which is why streaming routes want a much larger value.'),
        ),
    ]
