# Generated by Django 5.2.17 on 2026-09-21 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=254, unique=True)),
                ('locked_until', models.DateTimeField()),
                ('failed_count', models.IntegerField(default=0)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PanelAccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_domain', models.CharField(blank=True, default='', help_text='Public hostname for the panel, e.g. control.example.com. Blank keeps the panel on the loopback port only.', max_length=253)),
                ('is_published', models.BooleanField(default=False, help_text='Serve the panel on that hostname. Off until a certificate exists.')),
                ('ip_allowlist', models.JSONField(blank=True, default=list, help_text='CIDR ranges allowed to reach the panel. Empty means any address, which is the weakest setting here.')),
                ('require_mtls', models.BooleanField(default=False, help_text='Require a client certificate signed by the CA below. The strongest control available: an attacker without the certificate never reaches the login form at all.')),
                ('mtls_ca_path', models.CharField(blank=True, default='', help_text='PEM bundle of the CA that signs operator certificates', max_length=512)),
                ('hsts_seconds', models.IntegerField(default=31536000, help_text='Strict-Transport-Security max-age for the panel hostname')),
                ('require_totp', models.BooleanField(default=True, help_text='Require an authenticator code as well as a password. A password alone is one leak away from full control of every domain.')),
                ('login_rate_per_minute', models.IntegerField(default=10, help_text='Sign-in attempts allowed per minute, per client address')),
                ('api_rate_per_second', models.IntegerField(default=40, help_text='Requests per second allowed per client address across the panel')),
                ('lockout_threshold', models.IntegerField(default=5, help_text='Failed attempts before an account is locked. 0 disables locking.')),
                ('lockout_minutes', models.IntegerField(default=15, help_text='How long an account stays locked')),
                ('session_idle_minutes', models.IntegerField(default=60, help_text='Sign out after this long with no activity')),
                ('session_max_hours', models.IntegerField(default=12, help_text='Sign out this long after signing in, active or not')),
                ('expose_django_admin', models.BooleanField(default=False, help_text="Serve the Django admin on the public hostname. It is a much larger surface than the panel's own API and is blocked by default.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'panel access policy',
                'verbose_name_plural': 'panel access policy',
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, default='', help_text='Kept separately so the record survives the account being deleted', max_length=254)),
                ('action', models.CharField(help_text='HTTP method', max_length=16)),
                ('path', models.CharField(max_length=512)),
                ('status_code', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('summary', models.CharField(blank=True, default='', help_text="What happened, in the panel's own words", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('outcome', models.CharField(choices=[('success', 'Signed in'), ('bad_password', 'Wrong password'), ('bad_totp', 'Wrong authenticator code'), ('locked', 'Account locked'), ('blocked_ip', 'Address not allowed'), ('inactive', 'Account disabled')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username', '-created_at'], name='security_lo_usernam_8b5c66_idx')],
            },
        ),
        migrations.CreateModel(
            name='TotpDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=64)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Set once the operator has proved the app is working', null=True)),
                ('last_used_step', models.BigIntegerField(default=0, help_text='Time step of the last accepted code, so it cannot be reused')),
                ('recovery_codes', models.JSONField(blank=True, default=list, help_text='Hashed single-use codes for when the authenticator is lost')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
