# Generated by Django 5.2.17 on 2026-09-21 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficProtectionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Apply these limits to every public domain')),
                ('per_ip_connections', models.IntegerField(default=64, help_text='Concurrent connections one address may hold open. Low enough to bound a slow-connection attack, high enough not to break a browser opening several tabs behind one office address.')),
                ('per_ip_requests_per_second', models.IntegerField(default=50, help_text='Sustained request rate allowed from one address')),
                ('per_ip_burst', models.IntegerField(default=100, help_text='How far above that rate a short burst may go before requests are refused')),
                ('client_header_timeout', models.IntegerField(default=10, help_text='Seconds allowed to send request headers')),
                ('client_body_timeout', models.IntegerField(default=10, help_text='Seconds allowed between chunks of a request body')),
                ('denylist_enabled', models.BooleanField(default=True, help_text='Refuse blocked addresses without a response, before any other work')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'traffic protection policy',
                'verbose_name_plural': 'traffic protection policy',
            },
        ),
        migrations.CreateModel(
            name='BlockedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(db_index=True, help_text='A single address, or a range like 203.0.113.0/24', max_length=64, unique=True)),
                ('reason', models.CharField(choices=[('manual', 'Blocked by an operator'), ('abuse', 'Repeated abuse'), ('scanning', 'Scanning for vulnerabilities'), ('credentials', 'Guessing credentials')], default='manual', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Blocks expire unless this is empty, so a mistake heals itself', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'blocked addresses',
                'ordering': ['-created_at'],
            },
        ),
    ]
