# Generated by Django 5.2.17 on 2026-09-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Fully qualified domain name, e.g. api.example.com', max_length=253, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('ssl_cert_path', models.CharField(blank=True, default='', max_length=512)),
                ('ssl_key_path', models.CharField(blank=True, default='', max_length=512)),
                ('force_ssl_redirect', models.BooleanField(default=True, help_text='301 redirect HTTP → HTTPS when SSL is enabled')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
