# Generated by Django 5.2.17 on 2026-09-21 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcmeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Contact address for expiry warnings from the CA', max_length=254)),
                ('directory_url', models.URLField(choices=[('https://acme-v02.api.letsencrypt.org/directory', "Let's Encrypt (production)"), ('https://acme-staging-v02.api.letsencrypt.org/directory', "Let's Encrypt (staging)"), ('https://acme.zerossl.com/v2/DV90', 'ZeroSSL')], default='https://acme-v02.api.letsencrypt.org/directory', max_length=255)),
                ('agreed_to_tos', models.BooleanField(default=False)),
                ('external_account_kid', models.CharField(blank=True, default='', help_text='EAB key ID, required by ZeroSSL and some private CAs', max_length=255)),
                ('external_account_hmac', models.CharField(blank=True, default='', help_text='EAB HMAC key, stored as given by the CA', max_length=512)),
                ('is_default', models.BooleanField(default=False, help_text='Used when a domain requests a certificate without naming an account')),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'email'],
                'unique_together': {('email', 'directory_url')},
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(choices=[('acme', "Let's Encrypt / ACME"), ('self_signed', 'Self-signed'), ('manual', 'Uploaded manually')], default='acme', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Not issued yet'), ('requesting', 'Requesting'), ('active', 'Active'), ('renewing', 'Renewing'), ('expired', 'Expired'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('cert_path', models.CharField(blank=True, default='', max_length=512)),
                ('key_path', models.CharField(blank=True, default='', max_length=512)),
                ('chain_path', models.CharField(blank=True, default='', max_length=512)),
                ('subject_common_name', models.CharField(blank=True, default='', max_length=253)),
                ('san_domains', models.JSONField(blank=True, default=list, help_text='Subject Alternative Names covered by this certificate')),
                ('serial_number', models.CharField(blank=True, default='', max_length=128)),
                ('fingerprint_sha256', models.CharField(blank=True, default='', max_length=95)),
                ('not_before', models.DateTimeField(blank=True, null=True)),
                ('not_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('renew_before_days', models.IntegerField(default=30, help_text='Start renewing this many days before expiry')),
                ('last_issued_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('attempt_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acme_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='certificates.acmeaccount')),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='domains.domain')),
            ],
            options={
                'ordering': ['domain__name'],
            },
        ),
    ]
